export const STATUS_PENDING = 1;
export const STATUS_APPROVED = 2;
export const STATUS_REJECTED = 3;
export const TRANSACTION_TYPE_DOMESTIC_TRANSFER = 1;
export const TRANSACTION_TYPE_CROSS_BORDER = 2;


